### ISSUE TITLE
Error (404): "Not found"

### ISSUE THREAD

**Issue by sergey-nikitin-ai** [sapegin/sweet2#3]
Hi,

I'm trying configure fledermaus for my blog (https://github.com/snikitin-me/snikitin.me). But after npm start I have saw  Error (404): "Not found".

```
example.com@1.0.0 start C:\Users\Sergey\Documents\PROJECTS\static-snikitin.me
npm run server & npm run watch
example.com@1.0.0 server C:\Users\Sergey\Documents\PROJECTS\static-snikitin.me
http-server public -p 4242 -o

Starting up http-server, serving public
Available on:
  http:172.18.3.3:4242
  http:10.0.0.32:4242
  http:127.0.0.1:4242
Hit CTRL-C to stop the server
[Tue, 21 Mar 2017 13:21:48 GMT] "GET /" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"
[Tue, 21 Mar 2017 13:21:48 GMT] "GET /" Error (404): "Not found"
```

Could you tell me what I did wrong?

Regards,
Sergey.

**Comment by sapegin** [comment]
Try to build you site before starting a server.

**Comment by sergey-nikitin-ai** [comment]
I'm tried, but nothing has changed.

```
$ npm run build
example.com@1.0.0 build C:\Users\Sergey\Documents\PROJECTS\static-snikitin.me
babel-node src

Building the blog...
Done in a moment
```
After npm start I have Error (404): "Not found". Maybe I have not correctly located the source files
https://github.com/snikitin-me/snikitin.me/tree/master/source or are files in the wrong format?

**Comment by sapegin** [comment]
Do you need multilingual blog? If not you can remove half of the code ;-) Right now it doesn’t generate any documents because you don’t have a `lang` in frontmatter of any of them.

**Comment by sergey-nikitin-ai** [comment]
I do not need multilingual at the moent. I'am trying to run example with static site code. Following your advice I simplified the code and it was pushed at the branch https://github.com/snikitin-me/snikitin.me/tree/monolingual.
I was able to run the build, but after npm start I have got another error: 

```
[Thu, 23 Mar 2017 11:45:26 GMT] "GET /" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"
_http_outgoing.js:346
    throw new TypeError('The header content contains invalid characters');
    ^
TypeError: The header content contains invalid characters
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:346:11)
    at ResponseStream.(anonymous function) [as setHeader] (C:\Users\Sergey\Documents\PROJECTS\static-snikitin.me\node_modules\union\lib\response-stream.js:100:34)
    at C:\Users\Sergey\Documents\PROJECTS\static-snikitin.me\node_modules\ecstatic\lib\ecstatic\showdir.js:43:13
    at FSReqWrap.oncomplete (fs.js:123:15)
```

**Comment by sapegin** [comment]
Check the `documents` before you call `generatePages`, it’s empty right now.

**Comment by sapegin** [comment]
Closing this for now. Feel free to reopen with more information.
