### ISSUE TITLE
Update remark

### ISSUE THREAD

**Issue by wooorm** [sapegin/sweet2#4]
Hey! 👋

[`remark`](https://github.com/wooorm/remark/releases/tag/8.0.0) changed a bit recently. You should upgrade!

Feel free to ping me if you have questions.

P.S. have you seen [`rehype`](https://github.com/wooorm/rehype) and [it’s plugins](https://github.com/wooorm/rehype/blob/master/doc/plugins.md#list-of-plugins)? It’s pretty useful if you’re transforming HTML!

Cheers,
Titus

**Comment by sapegin** [comment]
Done in 598d7ff1d653c5fb6522737946cc556f871175b9.
